version: "3.9"

services:
# dbtの環境
  dbt:
    build:
      context: ./dbt
      dockerfile: Dockerfile
    container_name: 'dbt'
    # M1 macの場合
    #platform: linux/x86_64
    restart: always
    tty: true
    #expose:
    #  - "8050"
    #ports:
    #  - "8050:8050"
      # ほぼ同じ
      #- "127.0.0.1:8050:8050"
    working_dir: '/root/'
    volumes:
      - /Users/tanakatouma/vscode/dbt-docker/dbt/src/:/root/src/
#      - /Users/tanakatouma/Documents/Docker_volumes/ds_mlops/dash:/root/dash/

